swagger: "2.0"
info:
  title: DevCloud API
  version: 1.0.0
  termsOfService: http://10.11.20.102:6979/DevClouds
  contact:
    email: yaoyf@asiainfo.com
basePath: /v1
paths:
  /dc/checkout:
    get:
      tags:
      - dc
      description: checkout code
      operationId: DevCloudController.DevCloud checkout code
      parameters:
      - in: query
        name: project_name
        description: project name
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Result'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /dc/codecheck:
    get:
      tags:
      - dc
      description: code check
      operationId: DevCloudController.DevCloud code check
      parameters:
      - in: query
        name: project_name
        description: project name
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Result'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /dc/compile:
    get:
      tags:
      - dc
      description: compile code
      operationId: DevCloudController.DevCloud compile code
      parameters:
      - in: query
        name: project_name
        description: project name
        required: true
        type: string
      - in: query
        name: jdk_version
        description: jdk version {1.5 1.6 1.7 1.8}
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Result'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /dc/create:
    get:
      tags:
      - dc
      description: Create project
      operationId: DevCloudController.DevCloud Create Project
      parameters:
      - in: query
        name: project_name
        description: project name
        required: true
        type: string
      - in: query
        name: svn_url
        description: project svn
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Result'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /dc/pack:
    get:
      tags:
      - dc
      description: Pack project
      operationId: DevCloudController.DevCloud Pack Project
      parameters:
      - in: query
        name: project_name
        description: project name
        required: true
        type: string
      - in: query
        name: version
        description: project version
        required: true
        type: string
      - in: query
        name: isE
        description: 是否紧急发布Y/N
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Result'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /index/:
    get:
      tags:
      - index
      description: hellp api
      operationId: IndexController.GetAll
      responses:
        "200":
          description: hello api
  /task/add:
    get:
      tags:
      - task
      description: add task
      operationId: TaskController.AddTask
      parameters:
      - in: query
        name: project_name
        description: project_name
        required: true
        type: string
      - in: query
        name: spec
        description: 秒 分钟 小时 天 月 星期
        required: true
        type: string
      - in: query
        name: tasklist
        description: 从checkout;codecheck;compile|jdk_version;pack|project_version中组合,多个以分号隔开
        required: true
        type: string
      responses:
        "200":
          description: '{"status": 200,"task_in_estype":"crontask", "task_in_esid":id}'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /task/del:
    get:
      tags:
      - task
      description: delete task
      operationId: TaskController.DelTask
      parameters:
      - in: query
        name: taskid
        description: task id
        required: true
        type: string
      responses:
        "200":
          description: '{"status": 200}'
        "403":
          description: Forbidden
        "10016":
          description: Miss required parameter
  /task/getall:
    get:
      tags:
      - task
      description: Get all task
      operationId: TaskController.Get all Task
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.CronInfo'
        "403":
          description: Forbidden
definitions:
  models.CronInfo:
    title: CronInfo
    type: object
    properties:
      NextRunTime:
        type: string
      PreRunTime:
        type: string
      Project:
        type: string
      Spec:
        type: string
      TaskList:
        type: string
      TaskName:
        type: string
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Email:
        type: string
      Gender:
        type: string
  models.Result:
    title: Result
    type: object
    properties:
      _index:
        type: string
      _type:
        type: string
      ID:
        type: string
      PACKAGE_URL:
        type: string
      SONAR_URL:
        type: string
      current:
        type: string
      result:
        type: string
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Password:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Username:
        type: string
tags:
- name: dc
  description: |
    Operations about devclouds
- name: index
  description: |
    Operations about index
- name: task
  description: |
    Operations about task
